version: '3'
networks:
  restaurant-kata:
    driver: bridge
    ipam:
      driver: default
services:
  customer-actor:
    build: customer
    ports:
      - 5000:5000
    # volumes:
    #   - ./customer:/var/www/html:rw
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - APIs__GuestExperience=http://guestexperience:4010/
      - APIS__TableService=http://TableService:4010/
      - APIS__Billing=http://Billing:4010/
    # working_dir: /var/www/html
    # entrypoint: dotnet run --no-launch-profile
    networks:
      - restaurant-kata
  
  TableService:
    image: stoplight/prism:4
    ports:
      - "8082:4010"
    volumes:
      - ./services:/services
    command: mock -h 0.0.0.0 /services/TableService.yaml
    networks:
      - restaurant-kata

  guestexperience:
    image: stoplight/prism:4
    ports:
      - "8081:4010"
    volumes:
      - ./services:/services
    command: mock -h 0.0.0.0 /services/GuestExperience.yaml
    networks:
      - restaurant-kata

  Billing:
    image: stoplight/prism:4
    ports:
      - "8083:4010"
    volumes:
      - ./services:/services
    command: mock -h 0.0.0.0 /services/Billing.yaml
    networks:
      - restaurant-kata

  # c#
  # Delivery:
  #   image: mcr.microsoft.com/dotnet/core/sdk:3.1
  #   ports:
  #     - 8084:5000
  #   volumes:
  #     - ./customer:/var/www/html:rw
  #   working_dir: /var/www/html
  #   entrypoint: dotnet run
  #   networks:
  #     - restaurant-kata
  
  # node
  # Delivery:
  #   image: node:latest
  #   ports:
  #     - 8084:3000
  #   entrypoint: npm start
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./services/delivery:/var/www/html:rw
  #   networks:
  #     - restaurant-kata
